version: '3.8'
services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # Porta SMTP
      - "8025:8025" # Interface web para visualização de e-mails
    restart: always

  mercure:
    image: dunglas/mercure
    container_name: mercure
    ports:
      - "3000:80" # Porta HTTP para o hub Mercure
    environment:
      # Configuração mínima para Mercure
      MERCURE_PUBLISHER_JWT_KEY: "!changeThisMercureHubJWTSecretKey!"
      MERCURE_SUBSCRIBER_JWT_KEY: "!changeThisMercureHubJWTSecretKey!"
      ALLOW_ANONYMOUS: "1" # Permitir acesso anônimo
      CORS_ALLOWED_ORIGINS: "*" # Permitir CORS de qualquer origem
    restart: always
