version: '3.8'
services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # Porta SMTP
      - "8025:8025" # Interface web para visualização de e-mails
    restart: always

  mercure:
    image: dunglas/mercure
    container_name: mercure
    ports:
      - "3000:80" # Porta HTTP para o hub Mercure
    environment:
      # Configuração mínima para Mercure
      MERCURE_PUBLISHER_JWT_KEY: "!changeThisMercureHubJWTSecretKey!"
      MERCURE_SUBSCRIBER_JWT_KEY: "!changeThisMercureHubJWTSecretKey!"
      ALLOW_ANONYMOUS: "1" # Permitir acesso anônimo
      CORS_ALLOWED_ORIGINS: "*" # Permitir CORS de qualquer origem
    restart: always

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Porta padrão do RabbitMQ
      - "15672:15672" # Interface de gerenciamento do RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

  message_sender:
    build: ./message_sender
    container_name: message_sender
    depends_on:
      - rabbitmq
    volumes:
      - ./message_sender:/app
    command: ["python", "send_message.py"]

  message_listener:
    build: ./message_listener
    container_name: message_listener
    depends_on:
      - rabbitmq
    volumes:
      - ./message_listener:/app
    command: ["python", "listen_queue.py"]
