version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ broker
      - "15672:15672"  # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI

  mercure:
    image: dunglas/mercure
    container_name: mercure
    ports:
      - "80:80"
    environment:
      MERCURE_TLS: "0"
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisPublisherKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisSubscriberKey!'
      MERCURE_CORS_ALLOWED_ORIGINS: "*"
      SERVER_NAME: http://localhost
      ALLOWED_TOPICS: "*"
      ALLOWED_ORIGINS: "*"
      DEBUG: "true"

  # notification_service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: notification_service_mail
  #   working_dir: /app
  #   volumes:
  #     - ./python/notification_service:/app
  #   command: python listen_queue.py notification.email
  #   environment:
  #     - RABBITMQ_HOST=rabbitmq
  #     - RABBITMQ_USER=user
  #     - RABBITMQ_PASS=password
  #   depends_on:
  #     - rabbitmq
